name: Test Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to use the action locally
        uses: actions/checkout@v3.5.3

      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@jeantessier'

      - name: Output the answer
        run: echo "The answer is ${{ step.my-action.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected.  Expected 42 but was ${{ steps.my-action.outputs.answer }}"
          exit 1
